package greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import greendao.AuthorBean;
import com.wy.adbook.mvp.model.dao.BookChapterBean;
import com.wy.adbook.mvp.model.dao.BookCommentBean;
import com.wy.adbook.mvp.model.dao.BookHelpfulBean;
import com.wy.adbook.mvp.model.dao.BookHelpsBean;
import com.wy.adbook.mvp.model.dao.BookReviewBean;
import com.wy.adbook.mvp.model.dao.CollBookBean;
import com.wy.adbook.mvp.model.dao.DownloadTaskBean;
import com.wy.adbook.mvp.model.dao.ReviewBookBean;
import com.wy.adbook.mvp.model.entity.Account;
import com.wy.adbook.mvp.model.entity.book.bookread.BookDetailsBean;
import com.wy.adbook.mvp.model.entity.book.bookread.ChapterListBean;
import com.wy.adbook.view.readview.bean.BookRecordBean;

import greendao.AuthorBeanDao;
import greendao.BookChapterBeanDao;
import greendao.BookCommentBeanDao;
import greendao.BookHelpfulBeanDao;
import greendao.BookHelpsBeanDao;
import greendao.BookReviewBeanDao;
import greendao.CollBookBeanDao;
import greendao.DownloadTaskBeanDao;
import greendao.ReviewBookBeanDao;
import greendao.AccountDao;
import greendao.BookDetailsBeanDao;
import greendao.ChapterListBeanDao;
import greendao.BookRecordBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig authorBeanDaoConfig;
    private final DaoConfig bookChapterBeanDaoConfig;
    private final DaoConfig bookCommentBeanDaoConfig;
    private final DaoConfig bookHelpfulBeanDaoConfig;
    private final DaoConfig bookHelpsBeanDaoConfig;
    private final DaoConfig bookReviewBeanDaoConfig;
    private final DaoConfig collBookBeanDaoConfig;
    private final DaoConfig downloadTaskBeanDaoConfig;
    private final DaoConfig reviewBookBeanDaoConfig;
    private final DaoConfig accountDaoConfig;
    private final DaoConfig bookDetailsBeanDaoConfig;
    private final DaoConfig chapterListBeanDaoConfig;
    private final DaoConfig bookRecordBeanDaoConfig;

    private final AuthorBeanDao authorBeanDao;
    private final BookChapterBeanDao bookChapterBeanDao;
    private final BookCommentBeanDao bookCommentBeanDao;
    private final BookHelpfulBeanDao bookHelpfulBeanDao;
    private final BookHelpsBeanDao bookHelpsBeanDao;
    private final BookReviewBeanDao bookReviewBeanDao;
    private final CollBookBeanDao collBookBeanDao;
    private final DownloadTaskBeanDao downloadTaskBeanDao;
    private final ReviewBookBeanDao reviewBookBeanDao;
    private final AccountDao accountDao;
    private final BookDetailsBeanDao bookDetailsBeanDao;
    private final ChapterListBeanDao chapterListBeanDao;
    private final BookRecordBeanDao bookRecordBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        authorBeanDaoConfig = daoConfigMap.get(AuthorBeanDao.class).clone();
        authorBeanDaoConfig.initIdentityScope(type);

        bookChapterBeanDaoConfig = daoConfigMap.get(BookChapterBeanDao.class).clone();
        bookChapterBeanDaoConfig.initIdentityScope(type);

        bookCommentBeanDaoConfig = daoConfigMap.get(BookCommentBeanDao.class).clone();
        bookCommentBeanDaoConfig.initIdentityScope(type);

        bookHelpfulBeanDaoConfig = daoConfigMap.get(BookHelpfulBeanDao.class).clone();
        bookHelpfulBeanDaoConfig.initIdentityScope(type);

        bookHelpsBeanDaoConfig = daoConfigMap.get(BookHelpsBeanDao.class).clone();
        bookHelpsBeanDaoConfig.initIdentityScope(type);

        bookReviewBeanDaoConfig = daoConfigMap.get(BookReviewBeanDao.class).clone();
        bookReviewBeanDaoConfig.initIdentityScope(type);

        collBookBeanDaoConfig = daoConfigMap.get(CollBookBeanDao.class).clone();
        collBookBeanDaoConfig.initIdentityScope(type);

        downloadTaskBeanDaoConfig = daoConfigMap.get(DownloadTaskBeanDao.class).clone();
        downloadTaskBeanDaoConfig.initIdentityScope(type);

        reviewBookBeanDaoConfig = daoConfigMap.get(ReviewBookBeanDao.class).clone();
        reviewBookBeanDaoConfig.initIdentityScope(type);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        bookDetailsBeanDaoConfig = daoConfigMap.get(BookDetailsBeanDao.class).clone();
        bookDetailsBeanDaoConfig.initIdentityScope(type);

        chapterListBeanDaoConfig = daoConfigMap.get(ChapterListBeanDao.class).clone();
        chapterListBeanDaoConfig.initIdentityScope(type);

        bookRecordBeanDaoConfig = daoConfigMap.get(BookRecordBeanDao.class).clone();
        bookRecordBeanDaoConfig.initIdentityScope(type);

        authorBeanDao = new AuthorBeanDao(authorBeanDaoConfig, this);
        bookChapterBeanDao = new BookChapterBeanDao(bookChapterBeanDaoConfig, this);
        bookCommentBeanDao = new BookCommentBeanDao(bookCommentBeanDaoConfig, this);
        bookHelpfulBeanDao = new BookHelpfulBeanDao(bookHelpfulBeanDaoConfig, this);
        bookHelpsBeanDao = new BookHelpsBeanDao(bookHelpsBeanDaoConfig, this);
        bookReviewBeanDao = new BookReviewBeanDao(bookReviewBeanDaoConfig, this);
        collBookBeanDao = new CollBookBeanDao(collBookBeanDaoConfig, this);
        downloadTaskBeanDao = new DownloadTaskBeanDao(downloadTaskBeanDaoConfig, this);
        reviewBookBeanDao = new ReviewBookBeanDao(reviewBookBeanDaoConfig, this);
        accountDao = new AccountDao(accountDaoConfig, this);
        bookDetailsBeanDao = new BookDetailsBeanDao(bookDetailsBeanDaoConfig, this);
        chapterListBeanDao = new ChapterListBeanDao(chapterListBeanDaoConfig, this);
        bookRecordBeanDao = new BookRecordBeanDao(bookRecordBeanDaoConfig, this);

        registerDao(AuthorBean.class, authorBeanDao);
        registerDao(BookChapterBean.class, bookChapterBeanDao);
        registerDao(BookCommentBean.class, bookCommentBeanDao);
        registerDao(BookHelpfulBean.class, bookHelpfulBeanDao);
        registerDao(BookHelpsBean.class, bookHelpsBeanDao);
        registerDao(BookReviewBean.class, bookReviewBeanDao);
        registerDao(CollBookBean.class, collBookBeanDao);
        registerDao(DownloadTaskBean.class, downloadTaskBeanDao);
        registerDao(ReviewBookBean.class, reviewBookBeanDao);
        registerDao(Account.class, accountDao);
        registerDao(BookDetailsBean.class, bookDetailsBeanDao);
        registerDao(ChapterListBean.class, chapterListBeanDao);
        registerDao(BookRecordBean.class, bookRecordBeanDao);
    }
    
    public void clear() {
        authorBeanDaoConfig.clearIdentityScope();
        bookChapterBeanDaoConfig.clearIdentityScope();
        bookCommentBeanDaoConfig.clearIdentityScope();
        bookHelpfulBeanDaoConfig.clearIdentityScope();
        bookHelpsBeanDaoConfig.clearIdentityScope();
        bookReviewBeanDaoConfig.clearIdentityScope();
        collBookBeanDaoConfig.clearIdentityScope();
        downloadTaskBeanDaoConfig.clearIdentityScope();
        reviewBookBeanDaoConfig.clearIdentityScope();
        accountDaoConfig.clearIdentityScope();
        bookDetailsBeanDaoConfig.clearIdentityScope();
        chapterListBeanDaoConfig.clearIdentityScope();
        bookRecordBeanDaoConfig.clearIdentityScope();
    }

    public AuthorBeanDao getAuthorBeanDao() {
        return authorBeanDao;
    }

    public BookChapterBeanDao getBookChapterBeanDao() {
        return bookChapterBeanDao;
    }

    public BookCommentBeanDao getBookCommentBeanDao() {
        return bookCommentBeanDao;
    }

    public BookHelpfulBeanDao getBookHelpfulBeanDao() {
        return bookHelpfulBeanDao;
    }

    public BookHelpsBeanDao getBookHelpsBeanDao() {
        return bookHelpsBeanDao;
    }

    public BookReviewBeanDao getBookReviewBeanDao() {
        return bookReviewBeanDao;
    }

    public CollBookBeanDao getCollBookBeanDao() {
        return collBookBeanDao;
    }

    public DownloadTaskBeanDao getDownloadTaskBeanDao() {
        return downloadTaskBeanDao;
    }

    public ReviewBookBeanDao getReviewBookBeanDao() {
        return reviewBookBeanDao;
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

    public BookDetailsBeanDao getBookDetailsBeanDao() {
        return bookDetailsBeanDao;
    }

    public ChapterListBeanDao getChapterListBeanDao() {
        return chapterListBeanDao;
    }

    public BookRecordBeanDao getBookRecordBeanDao() {
        return bookRecordBeanDao;
    }

}
