server:
  port: 8093
zipkin:
  host: http://192.168.18.211
logging:
  level:
    root: INFO
    com:
      favorites: DEBUG
    org:
      hibernate: ERROR
      springframework:
        web: INFO
    ooh.chaos: debug
    ooh.chaos.aspect.TimeAspect: warn
    com.only: debug
  path: /log/payment-free
mybatis:
  type-aliases-package: com.only.tech.payment.mapper
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
mybatis-plus:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  type-aliases-package: com.only.tech.payment.mapper
  global-config:
    logic-delete-value: 0
    logic-not-delete-value: 1
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: false
spring:
  redis:
    database: 0
    host: www.weiyi.com
    password: null
    max-active: 8
    max-idle: 500
    max-wait: 1
    min-idle: 0
    port: 6379
    timeout: 5000ms
  rabbitmq:
    host: www.weiyi.com
    username: admin
    password: 123456
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  dubbo:
    application:
      id: payment-dubbo
      name: payment-dubbo
    protocol:
      name: dubbo
      port: 20893
    registry:
      address: zookeeper://www.weiyi.com:2181
    server: true
    provider:
      version: 2.0.0-free
    consumer:
      version: 2.0.0-free
      check: false
sharding:
  jdbc:
    config:
      sharding:
        default-database-strategy:
          inline:
            algorithm-expression: ds0
            sharding-column:
        tables:
          b_chapter:
            actual-data-nodes: ds0.b_chapter_$->{0..9}
            table-strategy:
              inline:
                algorithm-expression: b_chapter_$->{(cBID.intdiv(100))%10}
                sharding-column: cBID
    datasource:
      ds0:
        url: jdbc:mysql://www.weiyi.com:3306/pay_free?useUnicode=true&characterEncoding=UTF-8
        type: com.alibaba.druid.pool.DruidDataSource
        username: root
        password: WEIYI2018
        driver-class-name: com.mysql.jdbc.Driver
      names: ds0
wxpay:
  domain-url: http://moemoemoe.iok.la:30589
  notify-url: http://moemoemoe.iok.la:30589/wxpay/result/notify
  certPath: /pay/wx/apiclient_cert.p12
  expire-minute: 15
  sandbox: true
ali:
  notify-url: http://moemoemoe.iok.la:30589/alipay/result/notify
  expire-minute: 15
  sandbox: false
  bill-path: /data/ali/bill/